/* eslint-disable @typescript-eslint/no-explicit-any */
// propsDataIn: React.CSSProperties
export const useStyles = (propsDataIn: any) => ({
  card: {
    borderRadius: '10px',
    height: 211,
    justifyContent: 'space-between',
    elevation: 5,
    alignSelf: 'center',
    position: 'relative',
    ...propsDataIn?.dataIn?.card,
  },
  expandContainer: {
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 35 / 2,
    position: 'absolute',
    right: 15,
    display: 'flex',
    top: 10,
    elevation: 10,
    backgroundColor: propsDataIn?.theme.colors.white,
    ...propsDataIn?.dataIn?.expandContainer,
  },
  imageContainer: {
    paddingBottom: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '150px',
    margin: '0 auto',
    paddingTop: '26px',
    ...propsDataIn?.dataIn?.imageContainer,
  },
  cardNumber: {
    fontSize: 21,
    fontWeight: '500',
    alignSelf: 'center',
    textAlign: 'center',
    letterSpacing: 4,
    ...propsDataIn?.dataIn?.cardNumber,
  },
  footer: {
    paddingTop: '7px',
    paddingLeft: '20px',
    ...propsDataIn?.dataIn?.footer,
  },
  details: {
    fontSize: 14,
    fontWeight: '400',
    textTransform: 'uppercase',
    lineHeight: '22px',
    ...propsDataIn?.dataIn?.details,
  },
  nameExpirationContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    display: 'flex',
    ...propsDataIn?.dataIn?.nameExpirationContainer,
  },
  nameContainer: {
    width: '50%',
    display: 'flex',
    alignItems: 'center',
    ...propsDataIn?.dataIn?.nameContainer,
  },
  expirationContainer: {
    width: '40%',
    flexDirection: 'row',
    display: 'flex',
    paddingRight: '19px',
    alignItems: 'center',
    justifyContent: 'center',
    ...propsDataIn?.dataIn?.expirationContainer,
  },
  expLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    width: '60%',
    textAlign: 'end',
    marginRight: '10px',
    ...propsDataIn?.dataIn?.expLabel,
  },
  exp: {
    width: '40%',
    fontSize: 16,
    fontWeight: '400',
    ...propsDataIn?.dataIn?.exp,
  },
});
